# docker-compose.yml
version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '4000:4000'
      - '9229:9229'

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
